{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.3.3.jar",
          "url": "spring-boot-test-autoconfigure-3.3.3.jar",
          "size": 219314,
          "sha512": "1c12f1d4eeb9fbde8b000d2cda9f22b719f079427dcf17ae805cf45309352dac4210a54b98d70149097e62fe4fd77f5dc8f40cbaaa64e02aa3ae99b95c555f05",
          "sha256": "3fb4dbc55fdbefc3fa7f0518ee8c0839f5820b9f42c61fbdb6f2c390940bec7f",
          "sha1": "ebce486202d965dc984ff8013a8f87fdb9b6fe46",
          "md5": "0ead73470d6b8fde4709865f7ad8cb8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.3.3.jar",
          "url": "spring-boot-test-autoconfigure-3.3.3.jar",
          "size": 219314,
          "sha512": "1c12f1d4eeb9fbde8b000d2cda9f22b719f079427dcf17ae805cf45309352dac4210a54b98d70149097e62fe4fd77f5dc8f40cbaaa64e02aa3ae99b95c555f05",
          "sha256": "3fb4dbc55fdbefc3fa7f0518ee8c0839f5820b9f42c61fbdb6f2c390940bec7f",
          "sha1": "ebce486202d965dc984ff8013a8f87fdb9b6fe46",
          "md5": "0ead73470d6b8fde4709865f7ad8cb8d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.3.3-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-3.3.3-javadoc.jar",
          "size": 488818,
          "sha512": "2fbed42aa96aba16c4fd4e0b8262114f5efa6cbde0d49af43b193e35c8ec6215b9eedc0d30de4f58ff0abfaaffcb071104adc462aa9279df42159f46d108c332",
          "sha256": "57c7dc5ee2d3a7288c46fe8ff5702ea6ce7358dcbc354c214e73d024a666fd3f",
          "sha1": "a1acf7b3df21fbdf9ec1152581b15d31dbce9b70",
          "md5": "0ed1768fd8c9eb2cb8d9a244403ffb56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.3.3-sources.jar",
          "url": "spring-boot-test-autoconfigure-3.3.3-sources.jar",
          "size": 222205,
          "sha512": "8608bc65433b5b2e4cae11312a58f1d0b1de6dd82c1cece19846a6d474e7d2c2ff748bf74926ef97420af46a27085554d5e2f2b0b4a993d7cb069ae453f7f7cc",
          "sha256": "9c8c783f45437eb9cf6606acaeca892725a38048a1d0d2135e307124c81263b1",
          "sha1": "805451baeac770cefbb7216eb856de7ddb5f0427",
          "md5": "c04dcc343da357e8188e680544e7e15a"
        }
      ]
    }
  ]
}
